c_compiler:            # [win]
- vs2019               # [win]
cxx_compiler:          # [win]
- vs2019               # [win]
c_compiler:            # [osx and arm64]
  - clang_bootstrap    # [osx and arm64]
cxx_compiler:          # [osx and arm64]
  - clang_bootstrap    # [osx and arm64]
channel_targets:
  - conda-forge mlir_rc
channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
